Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,16 +67,19 @@ jobs:
           ${{ github.workspace }}/tool/data
     - run: pip install -r requirements.txt
     - run: |
+        set -e
+        echo "Running build setup..."
         ./build.sh setup
+        echo "Running build pack..."
         ./build.sh pack -p android -v ${{ inputs.subversion }} --no-zip
-        echo "Comprobando contenidos del directorio ./build..."
+        echo "Contents of ./build directory:"
         ls -R ./build
         if [ -f ./build/pack-android.mcpack ]; then
         mv ./build/pack-android.mcpack newb-x-android.mcpack
         elif [ -f ./build/nxcv-0.22-android.mcpack ]; then
         mv ./build/nxcv-0.22-android.mcpack newb-x-android.mcpack
         else
-        echo "Error: No se encontró el archivo esperado en ./build"
+        echo "Error: No .mcpack file found. Ensure build.sh is generating the required files."
         exit 1
         fi
     - uses: actions/upload-artifact@v4
