Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,7 +41,7 @@ jobs:
         Get-ChildItem -Path ./build
         $mcpack = Get-ChildItem -Path ./build -Filter "*.mcpack" | Select-Object -First 1
         if ($mcpack) {
-        Rename-Item -Path $mcpack.FullName -NewName "newb-x-windows.mcpack"
+        Rename-Item -Path $mcpack.FullName -NewName "newb-x-cv-windows.mcpack"
         } else {
         Write-Error "No .mcpack file found. Check build.bat or shader compilation."
         exit 1
@@ -69,7 +69,13 @@ jobs:
     - run: |
         ./build.sh setup
         ./build.sh pack -p android -v ${{ inputs.subversion }}
-        mv ./build/pack-android.zip newb-x-android.mcpack
+        ls -l ./build
+        if [ -f ./build/pack-android.zip ]; then
+        mv ./build/pack-android.zip newb-x-cv-android.mcpack
+        else
+        echo "Error: pack-android.zip not found in ./build"
+        exit 1
+        fi
     - uses: actions/upload-artifact@v4
       with:
         name: newb-x-android.mcpack
